### ISSUE TITLE
Jumping through the trace

### ISSUE THREAD

**Issue by francisanthony17** [path-visualiser/app#15]
currently we are able to step through the search trace by moving to the next search operation or moving to the next expansion

proposal:
We want to add an additional jumping mechanism to be able to do the following:
- move to the next distinct f value
- move to the next solution

perhaps implement this by introducing alternative behaviors for the fast forward button.

**Comment by Spaaaacccee** [comment]
Thanks @francisanthony17 

Since viewing solutions is a common use case, we should make it very easy to achieve this

**Proposal**

- Introduce a dropdown in the steps view that filters events by event type.

**Comment by Spaaaacccee** [comment]
In [28d4b97](https://github.com/path-visualiser/app/commit/28d4b97c8a2fb70fd1be3b14614e89a70d208324), we introduced this feature.

- [x] Introduce a dropdown in the steps view that filters events by event type.

<img width="329" alt="image" src="https://github.com/path-visualiser/app/assets/15244945/90e0ee28-402a-4acd-b195-70b0baa13840">
