### ISSUE TITLE
Multiple parents

### ISSUE THREAD

**Issue by dharabor** [path-visualiser/app#24]
Sometimes there can be several equivalent paths to a node. Some algorithms keep all the optimal-cost parents so they can identify the set of all optimal paths. We can add support for these methods by extending the "pid" label from a single value to a list. When showing the path back to the root for a node with multiple parents, we build up the closure of all nodes, rather than at the moment, which just shows a single path.

**Comment by Spaaaacccee** [comment]
Duplicate of #2
